/* A bundled IFC4 sample WITH real swept-solid geometry — generated by the studio's
 * own building engine + IFC writer, so the 3D model is a complete structure, not a
 * mock-up: foundations + ground beams, floor slabs, a column grid, edge beams, a
 * core, façade walls with windows and entrance doors, interior partitions with
 * doors off real corridors, stairs decomposed into flights/landings/railings,
 * floor finishes + suspended ceilings, parapets, a roof, IfcSpaces for every room
 * and corridor, property sets and IfcTypeObjects — organised under a full
 * project → site → building → storey tree. web-ifc tessellates every solid. */

import { buildMassing } from './massing'
import { buildBuilding } from './building'
import { toIfc } from './building-ifc'

// A compact four-storey block (~600 m² per plate) keeps in-browser tessellation
// quick while still carrying every layer of the anatomy.
export const SAMPLE_IFC_GEO: string = toIfc(
  buildBuilding(
    buildMassing({ gfa: 2_400, progress: 100, storeys: 4, shape: 'rect' }),
    { coreRatio: 0.18, wwr: 0.5, bayWidth: 3.6, roomSize: 10 },
  ),
  { name: 'Meridian Tower', storeyHeight: 3.5 },
)
